# Generated by Django 4.0.4 on 2022-05-14 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_rename_categorias_modelcategoria_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='modelCategoria',
            new_name='Categoria',
        ),
    ]
